### PR TITLE
8.2XS82ECU1041

### PR DESCRIPTION
**Pull request by gduperrey**

### CODE REVIEW

**Review by andSmv — APPROVED** [review]

**Review by benjamreis — APPROVED** [review]

**Comment by Wescoeur** [comment]
No changelog entry? :)

**Comment by gduperrey** [comment]
Not from quite sometime in the source file. So i don't add anything more in it. On this rpm, as we don't add our entries in the past, i keep the same way to do it.

**Comment by Wescoeur** [comment]
I'm not sure to understand. In the previous merge, we have one entry:
https://github.com/xcp-ng-rpms/linux-firmware/commit/016362c840f79d5ec99c7ede8d558c0ec9da4374#diff-3287de9435054126053275b264ea4992d9f2354c4641dc6f59baebfcd2edd7a0R78-R82

Also regarding this PR, we have a new version in the spec file, so we should have at least an upstream changelog entry.

**Comment by gduperrey** [comment]
Is that better like this?

**Review by Wescoeur — APPROVED** [review]

**Pull request merged**
